name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3.8.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.14
      - name: Install Proppo
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Test
        run: |
          ./test
